#### Build an Artificial Neural Network by implementing the Backpropagation algorithm and test the same using appropriate data sets. Vary the activation functions used and compare the results.

In [1]:
from keras.models import Sequential
from keras.layers import Dense, Activation
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split

c:\Users\hp\.conda\envs\example\Lib\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED


In [10]:
from tensorflow.keras.optimizers import SGD

In [3]:
#Import the iris data
iris = datasets.load_iris()
X, y = datasets.load_iris(return_X_y=True)

print(X)



[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [5]:
# Define the network model and its argument
#Set the number of neurons/nodes for each layer

model = Sequential()
model.add(Dense(2, input_shape= (4,)))
model.add(Activation('sigmoid'))
model.add(Dense(1))
model.add(Activation('sigmoid'))

model.compile(loss='mean_squared_error', optimizer='sgd', metrics=['accuracy'])
model.fit(X_train,y_train, batch_size=32, epochs=3)

c:\Users\hp\.conda\envs\example\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/3
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.3111 - loss: 1.1224
Epoch 2/3
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.3111 - loss: 1.1021 
Epoch 3/3
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.3111 - loss: 1.0851 


In [6]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │            10 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation (Activation)         │ (None, 2)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_1 (Activation)       │ (None, 1)              │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 15 (64.00 B)

 Trainable params: 13 (52.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2 (12.00 B)

In [11]:

sgd = SGD(learning_rate = 0.01, decay=1e-6, momentum=0.9, nesterov= True)

model.compile(loss='categorical_crossentropy', optimizer=sgd, metrics=['accuracy'])
model.fit(X_train, y_train, batch_size=32, epochs=200, validation_split=0.1)
model.summary()

Epoch 1/200


c:\Users\hp\.conda\envs\example\Lib\site-packages\keras\src\optimizers\base_optimizer.py:86: UserWarning: Argument `decay` is no longer supported and will be ignored.
  warnings.warn(


c:\Users\hp\.conda\envs\example\Lib\site-packages\keras\src\losses\losses.py:33: SyntaxWarning: In loss categorical_crossentropy, expected y_pred.shape to be (batch_size, num_classes) with num_classes > 1. Received: y_pred.shape=(None, 1). Consider using 'binary_crossentropy' if you only have 2 classes.
  return self.fn(y_true, y_pred, **self._fn_kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 371ms/step - accuracy: 0.2963 - loss: 0.0000e+00 - val_accuracy: 0.4444 - val_loss: 0.0000e+00
Epoch 2/200
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.2963 - loss: 0.0000e+00 - val_accuracy: 0.4444 - val_loss: 0.0000e+00
Epoch 3/200
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.2963 - loss: 0.0000e+00 - val_accuracy: 0.4444 - val_loss: 0.0000e+00
Epoch 4/200
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.2963 - loss: 0.0000e+00 - val_accuracy: 0.4444 - val_loss: 0.0000e+00
Epoch 5/200
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.2963 - loss: 0.0000e+00 - val_accuracy: 0.4444 - val_loss: 0.0000e+00
Epoch 6/200
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.2963 - loss: 0.0000e+00 - val_accuracy: 0.4444 - val_loss: 0.0000e+00
Epoch 7/200
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.2963 - loss: 0.0000e+00 - val_accuracy: 0.4444 - val_loss: 0.0000e+00
Epoch 8/200
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.3086 - lo

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │            10 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation (Activation)         │ (None, 2)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_1 (Activation)       │ (None, 1)              │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 28 (116.00 B)

 Trainable params: 13 (52.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 15 (64.00 B)

In [12]:
score = model.evaluate(X_test, y_test)
print(score)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.7500 - loss: 0.0000e+00
[0.0, 0.75]


- This simple Sequential model has an accuracy score of 75%
- `mean_squared_error` had an accuracy =~ 0.33
- `categorical_crossentropy` =~0.75

-Test set was 0.4

#### Improving the model

In [14]:
from sklearn.preprocessing import StandardScaler

scaler= StandardScaler()
X_train= scaler.fit_transform(X_train)
X_test= scaler.transform(X_test)

In [ ]:
# Building a simple neural network
model2= Sequential()
# Add a relu activation function to introduce non-linearity to the network
model2.add(Dense(16, activation='relu', input_shape=(4,))) #Iris dataset contains exactly 4 features
model2.add(Dense(12, activation='relu', input_shape = (4,)))
model2.add(Dense(3, activation='softmax'))

c:\Users\hp\.conda\envs\example\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [18]:
#Define SGD with specific parameters
custom_sgd = SGD(
    learning_rate = 0.01,
    momentum = 0.9,
    nesterov= True
)

#Compile the model
model2.compile(loss='sparse_categorical_crossentropy', optimizer = custom_sgd, metrics=['accuracy'])

#Fit the model
history = model2.fit(
    x= X_train,
    y=y_train,
    epochs=150, 
    batch_size=16,
    validation_split=0.1,
    verbose=1
)

#Evaluate the model
test_loss, test_acc = model2.evaluate(X_test, y_test)
print(f'Test accuracy: {test_acc:4f}')

Epoch 1/150


7/7 ━━━━━━━━━━━━━━━━━━━━ 3s 202ms/step - accuracy: 0.1759 - loss: 1.5229 - val_accuracy: 0.0000e+00 - val_loss: 1.3150
Epoch 2/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.3889 - loss: 1.1001 - val_accuracy: 0.6667 - val_loss: 0.9327
Epoch 3/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.7500 - loss: 0.9253 - val_accuracy: 0.7500 - val_loss: 0.7640
Epoch 4/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7963 - loss: 0.8011 - val_accuracy: 0.7500 - val_loss: 0.6222
Epoch 5/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.8519 - loss: 0.6914 - val_accuracy: 0.7500 - val_loss: 0.5134
Epoch 6/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.8704 - loss: 0.5962 - val_accuracy: 0.8333 - val_loss: 0.4355
Epoch 7/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8889 - loss: 0.5150 - val_accuracy: 0.8333 - val_loss: 0.3718
Epoch 8/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8611 - loss: 0.4485 - val_accuracy: 0.8333 - val_loss: 0.3250

`accuracy` for *model2* is: 1.000
- This indicates that it correctly classified each species in the Iris dataset

`  Improvements include`
1. Scaling the dataset first
2. Using `ReLu` activation functions at the hidden layers 
3. Using a `sparse_categorical_crossentropy` loss since the target is multi-class and is integer values (0,1,2)
4. Using a custom sgd optmizer